title: Sretno Srce
description: Ako te muči neki ljubavni ili seksualni problem, možda ti mogu dati neki koristan savjet. Ljubav komplicirana i ponekad nam treba pomoć.
baseurl: ""
url: https://www.sretnosrce.org
author:
  name: Matija Marohnić
  picture: /images/matija.jpg
  facebook: silvenon
  twitter: silvenon

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

paginate: 5
paginate_path: /str/:num/

logo: /images/og.png
facebook:
  app_id: 527606337428241
  publisher: srcesretno
social:
  links:
    - https://www.facebook.com/srcesretno/
github:
  url: https://www.sretnosrce.org
gauges_id: 55c5e80592c6ac728500b314

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - test
  - images/logo.sketch
  - CNAME

sass:
  sass_dir: styles
  style: compressed

permalink: /:title/

collections:
  - facts

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:title/
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
      permalink: /blog/:title/
