# Site settings
title: Sretno Srce
description: > # this means to ignore newlines until "baseurl:"
  Ako te muči neki ljubavni ili seksualni problem, možda ti mogu dati
  neki koristan savjet. Rado pomažem ljudima u takvim situacijama,
  jer je ljubav komplicirana i ponekad nam treba pomoć.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://sretnosrce.org # the base hostname & protocol for your site

fb_id: 1224905490
gauges_id: 55c5e80592c6ac728500b314

# Build settings
port: 9000
markdown: kramdown
sass:
  sass_dir: styles
  style: compressed
