# Site settings
title: Sretno Srce
description: Ako te muči neki ljubavni ili seksualni problem, možda ti mogu dati neki koristan savjet. Ljubav komplicirana i ponekad nam treba pomoć.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://sretnosrce.org # the base hostname & protocol for your site

gems:
  - jekyll-redirect-from

fb_id: 1224905490
fb_username: matijamm
fb_page: pages/Sretno-Srce/132649877076108
gauges_id: 55c5e80592c6ac728500b314

# Build settings
port: 9000
permalink: /pitanja/:title
markdown: kramdown
sass:
  sass_dir: styles
  style: compressed

# http://stackoverflow.com/a/23555679/1247274
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
